MyFirst_Application/config/routes.rb
MyFirstApplication::Application.routes.draw do
  resources :students

    root :to => 'students#new'

end

MyFirst_Application/app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :Address, :age, :description, :first_name, :last_name, :stream, :title
end

MyFirst_Application/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

MyFirst_Application/app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def new
		@student = Student.new
	end


	def create
		@student = Student.new(params[:student])
	   if @student.save
	    redirect_to(:controller => 'students' , :action => 'index')
	   end
	end



	def show
	 	@student = Student.find_by_id(params[:id])
	end	



	def index
		@students = Student.all
	end



	def edit
	  @student  = Student.find_by_id(params[:id])
	 end



	def update
		@student = Student.find_by_id(params[:id])

		if @student.update_attributes(params[:student])
		    redirect_to(:controller => 'students' , :action => 'new')
		end
	end



	def destroy
      @student = Student.find(params[:id])
      @student.destroy
    end
  

end

MyFirst_Application/app/helpers/application_helper.rb
module ApplicationHelper
end

MyFirst_Application/app/helpers/students_helper.rb
module StudentsHelper
end

MyFirst_Application/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApplication</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

MyFirst_Application/app/views/students/_form.html.erb
<%= form_for @student do |f| %> 


  <p> <%= f.label :title %>:
  <%= f.text_field :title %><br /> </p>
  <p> 
  <%= f.label :first_name %>:
  <%= f.text_field :first_name %><br /> </p>
  <p>
  <%= f.label :last_name %>:
  <%= f.text_field :last_name %><br /> </p>
  <p>
  <%= f.label :age %>:
  <%= f.text_field :age%><br /> </p>
  <p>
  <%= f.label :stream %>:
  <%= f.text_field :stream %><br /> </p>
  <p>
  <%= f.label :Address %>:
  <%= f.text_field :Address %><br /> </p>

  <p>
  <%= f.label :description %>:
  <%= f.text_field :description %><br />
  </p>
  <%= f.submit %>

 <% end %>

MyFirst_Application/app/views/students/edit.html.erb
<%= render 'form' %>

MyFirst_Application/app/views/students/index.html.erb
<html>
<head>
	<title> </title>
</head>
<body>

	<p> <%= link_to("Create New Entry" , :controller => 'students' , :action => 'new') %> <br/> </p>

<%= @students.each do |s| %>
<p> Title : <%= s.title %> <br/> </p>
<p> First Name : <%= s.first_name %> <br/> </p>
<p> Last Name : <%= s.last_name %> <br/> </p>
<p> Age : <%= s.age %> <br/> </p>
<p> Stream : <%= s.stream %> <br/> </p>
<p> Address : <%= s.Address %> <br/> </p>
<p> Description : <%= s.description %> <br/> </p>

 <p>  <%= link_to 'Delete Entry', student_path(s), method: :delete, data: { confirm: 'Are you sure?' } %> ||



      <%= link_to("Edit", :controller => 'students', :action => 'edit', :id => s.id ) %>  ||

     <%= link_to("Show" , :controller => 'students' , :action => 'show' , :id => s.id ) %> 
 </p>

<% end %>


</body>
</html>

MyFirst_Application/app/views/students/new.html.erb
<%= render 'form' %>

MyFirst_Application/app/views/students/show.html.erb
<html>
<head>
	<title> </title>
</head>
<body>
 

Title : <%= @student.title %> <br/>
First Name : <%= @student.first_name %> <br/>
Last Name : <%= @student.last_name %> <br/>
Age : <%= @student.age %> <br/>
Stream : <%= @student.stream %> <br/>
Address : <%= @student.Address %> <br/>
Description : <%= @student.description %> <br/>


</body>
</html>